import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / "src"))

import logging
import threading
import time
import tkinter as tk
from tkinter import messagebox

from maze_generator import generate_maze
from maze_solver.stats import complexity_score, format_complexity_score, maze_statistics
from pathfinding_algorithms import SOLVER_REGISTRY
from render import Render

logger = logging.getLogger(__name__)


class MazeSolverApp:
    def __init__(self, root):
        self.root = root
        self.render = Render(root, self)
        self.timer_running = False
        self.start_time = None
        self.elapsed_time = 0
        self.timer_id = None
        self.maze = None
        self.solving = False
        self.autogenerated_seed = None  # Track the last autogenerated seed
        self.stop_requested = False  # Add this flag for stopping the solver
        self.steps = 0
        self.show_completion_dialog = True

        # Bind keys to quit the application
        self.root.bind("<Escape>", self.quit_application)
        self.root.bind("q", self.quit_application)

    def quit_application(self, _=None):
        """Cleanly quit the application."""
        print("Quitting the application...")
        self.stop_requested = True
        self.stop_timer()
        self.root.quit()  # This will close the Tkinter loop
        try:
            self.root.destroy()  # This will clean up and destroy the window
        except tk.TclError:
            pass
        print("Application exited.")

    def start_timer(self):
        if not self.timer_running:
            self.timer_running = True
            self.start_time = time.time() - self.elapsed_time
            self.update_timer()

    def schedule_ui(self, callback, *args):
        try:
            self.root.after(0, callback, *args)
        except (RuntimeError, tk.TclError) as exc:
            if not self.stop_requested:
                logger.warning("Unable to schedule Tkinter UI callback: %s", exc)

    def stop_timer(self):
        if self.timer_running:
            self.timer_running = False
            if self.timer_id:
                self.root.after_cancel(self.timer_id)

    def reset_timer(self):
        self.stop_timer()
        self.elapsed_time = 0
        self.render.update_timer_label("00:00")

    def update_timer(self):
        if self.timer_running:
            self.elapsed_time = time.time() - self.start_time
            minutes = int(self.elapsed_time // 60)
            seconds = int(self.elapsed_time % 60)
            self.render.update_timer_label(f"{minutes:02d}:{seconds:02d}")
            self.timer_id = self.root.after(1000, self.update_timer)

    def generate_maze(self, auto_solve=False):
        params = self.render.get_maze_parameters()
        if params is None:
            return  # Invalid parameters, abort

        self.request_stop_solver(show_message=False)
        self.reset_timer()
        self.render.set_status("Generating maze...")

        # Get additional parameters from the new sliders
        dead_ends = int(self.render.dead_ends_scale.get())
        branching_factor = int(self.render.branching_factor_scale.get())
        connectedness = int(self.render.connectedness_scale.get()) * 10
        # Generate maze in a separate thread to avoid freezing the UI
        worker = threading.Thread(
            target=self._generate_maze_thread,
            args=(params, dead_ends, branching_factor, connectedness, auto_solve),
            daemon=True,
        )
        worker.start()

    def _generate_maze_thread(self, params, dead_ends, branching_factor, connectedness, auto_solve):
        try:
            # Check if the seed input is empty or if it's the autogenerated seed
            seed_input = params["seed"]
            if seed_input is None or str(seed_input) == self.autogenerated_seed:
                seed = None  # Force the generator to create a new random seed
            else:
                seed = seed_input  # Use the user-provided seed

            # Call generate_maze with the seed
            maze, used_seed = generate_maze(
                rows=params["rows"],
                cols=params["cols"],
                generation_algorithm=params["generation_algorithm"],
                seed=seed,
                dead_ends=dead_ends,
                branching_factor=branching_factor,
                connectedness=connectedness,
            )

            self.maze = maze

            # If the seed was autogenerated (seed=None), update the seed field
            if seed is None:
                self.autogenerated_seed = str(used_seed)  # Track the new autogenerated seed
                self.schedule_ui(self.update_seed_entry, str(used_seed))
            else:
                self.autogenerated_seed = None  # Reset if a user-provided seed is used

            # Update the UI in the main thread
            self.schedule_ui(self.render.draw_maze, self.maze)
            self.schedule_ui(self.update_maze_stats)
            self.schedule_ui(self.render.set_status, f"Maze ready | seed {used_seed}")
            if auto_solve:
                self.schedule_ui(lambda: self.solve_maze(show_dialog=False))
            # self.root.after(0, self.start_timer)
            print(f"Maze generated with seed: {used_seed}")

        except Exception as e:
            print(f"Error generating maze: {e}")
            self.schedule_ui(messagebox.showerror, "Error", f"An error occurred while generating the maze:\n{e}")

    def update_seed_entry(self, seed: str):
        self.render.seed_entry.delete(0, tk.END)
        self.render.seed_entry.insert(0, seed)

    def solve_maze(self, show_dialog=True):
        if self.maze is None or self.maze.size == 0:  # Adjust the maze check to avoid ambiguity
            messagebox.showwarning("No Maze", "Please generate a maze first.")
            return
        if self.solving:
            self.request_stop_solver(show_message=False)
            return

        self.solving = True
        self.stop_requested = False  # Reset the flag when starting
        self.reset_timer()
        self.start_time = time.time()
        self.start_timer()
        self.steps = 0
        self.show_completion_dialog = show_dialog

        # Get selected algorithm
        algorithm = self.render.update_algorithm_selection()

        solver = SOLVER_REGISTRY.get(algorithm)
        if solver is None:
            messagebox.showerror("Error", f"Unknown algorithm: {algorithm}")
            self.solving = False
            self.stop_timer()
            return
        self.solver_generator = solver(self.maze, (1, 1), (self.maze.shape[0] - 2, self.maze.shape[1] - 2))
        self.render.draw_maze(self.maze)
        self.update_maze_stats()
        self.render.set_status(f"Running {algorithm}...")

        # Start the solving process
        self.root.after(0, self._process_solver_step)

    def _process_solver_step(self):
        if self.stop_requested:
            self.solving = False
            self.stop_timer()
            print("Solver stopped by user.")
            return
        try:
            action, cell, steps = next(self.solver_generator)
            self.steps = steps

            if action == "visit":
                self.render.mark_visited(cell)
            elif action == "enqueue":
                self.render.mark_frontier(cell)
            elif action == "path":
                self.render.mark_path(cell)
            elif action == "done":
                self.solving = False
                self.stop_timer()
                self.show_summary()
                return

            # Schedule the next step
            if self.steps % 10 == 0:
                self.render.set_status(f"{self.render.update_algorithm_selection()} | steps {self.steps}")
            self.root.after(4, self._process_solver_step)
        except StopIteration:
            self.solving = False
            self.stop_timer()
            self.show_summary()

    def show_summary(self):
        elapsed_time = time.time() - self.start_time if self.start_time else 0
        params = self.render.get_maze_parameters() or {}
        algorithm = self.render.update_algorithm_selection() or "Unknown"
        self.render.set_status(f"Complete | {algorithm} | steps {self.steps or 0}")
        summary = (
            f"Algorithm: {algorithm}\n"
            f"Time Taken: {elapsed_time:.2f} seconds\n"
            f"Steps: {self.steps or 0}\n"
            f"Maze Size: {params.get('rows', '?')}x{params.get('cols', '?')}\n"
            f"Generation Algorithm: {params.get('generation_algorithm', 'Unknown')}\n"
            f"Seed: {params.get('seed', 'None')}"
        )
        if self.show_completion_dialog:
            messagebox.showinfo("Maze Solved!", summary)

    def update_maze_stats(self):
        if self.maze is None:
            return
        stats = maze_statistics(self.maze)
        algorithm = self.render.update_algorithm_selection()
        algorithm_info = self.render.algorithm_info_for(algorithm)
        score = format_complexity_score(complexity_score(algorithm_info, stats, max(1, self.steps or 1)))
        self.render.update_maze_stats(stats, score)

    def select_algorithm_and_restart(self):
        self.render.update_algorithm_panel()
        if self.maze is None:
            self.render.set_status("Select a generator, then generate a maze.")
            return
        self.generate_maze(auto_solve=True)

    def request_stop_solver(self, show_message=True):
        if not self.solving:
            if show_message:
                messagebox.showinfo("Not Solving", "No solving process is currently running.")
            return
        self.stop_requested = True
        self.solving = False
        self.stop_timer()
        self.render.set_status("Stopped")
        if show_message:
            messagebox.showinfo("Stop Solving", "Maze solver stopped.")

    def stop_solving(self):
        self.request_stop_solver(show_message=True)


if __name__ == "__main__":
    root = tk.Tk()
    root.title("Maze Solver")
    app = MazeSolverApp(root)

    try:
        root.mainloop()  # Start the Tkinter event loop
    except KeyboardInterrupt:
        print("\nKeyboardInterrupt detected. Exiting the application cleanly...")
        app.quit_application()  # Call the quit method to clean up
