"""Maze generation and pathfinding toolkit."""

from maze_solver.algorithms import (
    ALGORITHM_REGISTRY,
    SOLVER_REGISTRY,
    a_star_generator,
    bellman_ford_generator,
    bfs_generator,
    bidirectional_bfs_generator,
    dead_end_filling_generator,
    dfs_generator,
    dijkstra_generator,
    flood_fill_generator,
    greedy_best_first_generator,
    iddfs_generator,
    lee_generator,
    left_hand_rule_generator,
    pledge_generator,
    random_mouse_generator,
    right_hand_rule_generator,
    spfa_generator,
    tremaux_generator,
    uniform_cost_generator,
)
from maze_solver.generation import GENERATION_REGISTRY, generate_maze

__all__ = [
    "ALGORITHM_REGISTRY",
    "GENERATION_REGISTRY",
    "SOLVER_REGISTRY",
    "a_star_generator",
    "bellman_ford_generator",
    "bidirectional_bfs_generator",
    "bfs_generator",
    "dead_end_filling_generator",
    "dfs_generator",
    "dijkstra_generator",
    "flood_fill_generator",
    "generate_maze",
    "greedy_best_first_generator",
    "iddfs_generator",
    "lee_generator",
    "left_hand_rule_generator",
    "pledge_generator",
    "random_mouse_generator",
    "right_hand_rule_generator",
    "spfa_generator",
    "tremaux_generator",
    "uniform_cost_generator",
]
